# api call for create movies
POST http://127.0.0.1:8000/movie/
Content-Type: application/json
Authorization: Basic user:user@123

{
    "title": "JohnWick 4",
    "year": "2022",
    "language": "english",
    "genre": "action",
    "director": "jose",
    "run_time": 140
}


# api call for list movies
###
GET http://127.0.0.1:8000/movie/
Accept: application/json
Authorization: Basic user:user@123



# api  call for retrieve movie
###
GET http://127.0.0.1:8000/movie/9/
Accept: application/json
Authorization: Basic user:user@123



# api call for update movie
###
PUT http://127.0.0.1:8000/movie/2/
Content-Type: application/json
Authorization: Basic user:user@123

{
  "title": "Minnal Murali",
  "year": "2023",
  "language": "malayalam",
  "genre": "action",
  "run_time": 50,
  "director": "Basil Joseph"
}



# api call for delete movie
###
DELETE http://127.0.0.1:8000/movie/5/
Authorization: Basic user:user@123


# api call for register user
###
POST http://127.0.0.1:8000/register/
Content-Type: application/json

{
  "username":"user",
  "password":"user@123",
  "email":"user@gamil.com",
  "first_name":"user",
  "last_name":"u"
}