# Generated by Django 6.0.1 on 2026-01-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('year', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('malayalam', 'malayalam'), ('tamil', 'tamil'), ('telungu', 'telungu'), ('kannada', 'kanada')], default='malayalam', max_length=200)),
                ('genre', models.CharField(choices=[('action', 'action'), ('comedy', 'comedy'), ('drama', 'drama'), ('thriller', 'thriller'), ('fiction', 'fiction')], default='action', max_length=100)),
                ('run_time', models.PositiveIntegerField()),
                ('director', models.CharField(max_length=200)),
            ],
        ),
    ]
